const mongoose=require('mongoose')
let model=new mongoose.Schema({
    id:Number,
    username:String,
    password:String,
    name:String,
    branch:String,
    section:String,
    semester:Number,
    gender:String,
    email:String,
    mobile:Number,
    attendence:[
        {
            subject:String,
            lectures_conducted:Number,
            lectures_attended:Number,
            percentage:Number
        }   
    ],
    fees:{
        semester:Number,
        current_fee_status:String,
        amount_due:Number,
        payment_history:[
            {
                semester:Number,
                transaction_status:String,
                transaction_id:Number,
                amount:Number
            }
        ]
    },
    library:{
        borrowed_books:[String],
        due_date:[Date]
    },
    hostel:{
        allocated_room:String,
        allocated_hostel:String
    },
    timetable:[
        {
            day:String,
            slot1:String,
            slot2:String,
            slot3:String,
            slot4:String,
            slot5:String,
            slot6:String,
            slot7:String,
            slot8:String,
            slot9:String
        }
    ],
    marks:[
        {
            semester:Number,
            sem_marks_total:[
                {subject: String,
                    sub_marks:Number
                }
            ]
        }
    ]
})

module.exports=new mongoose.model('model',model)